# [tool.poetry]
# name = "neat"
# version = "0.1.0"
# description = ""
# authors = ["Softstream <softstream.link@gmail.com>"]
# readme = "readme.md"
# packages = [{ include = "links_core", from = "./src" }]

# [tool.poetry.dependencies]
# python = "^3.12"


# [build-system]
# requires = ["poetry-core"]
# build-backend = "poetry.core.masonry.api"
[tool.flit]
metadata = "pyproject.toml"
module = "links_core"

[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"


[tool.pytest.ini_options]
testpaths = ["tests"]
cache_dir = "./target/.pytest_cache"
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"