name: Push Test Build
on:
  push:
      branches:
        - '*'
        - '!main'

jobs:
  test-matrix:
    uses: softstream-link/workflows/.github/workflows/setuptools-pytest-matrix-py3.yml@v1
    with:
      fail-fast: false
    
  publish-pypi-test:
    needs: test-matrix
    uses: softstream-link/workflows/.github/workflows/setuptools-twine-pypi-publish.yml@v1
    with:
      environment: test
  
  



  