name: Pull/Master Control build
on:
  pull_request:
  push:
      branches:
        - 'main'

jobs:
  test-matrix:
    uses: softstream-link/workflows/.github/workflows/setuptools-pytest-matrix-py3.yml@v1
    with:
      fail-fast: false
  



  