name: Push Test Build
on:
  push:
      branches:
        - '*'
        - '!master'

jobs:
  test-matrix:
    uses: softstream-link/workflows/.github/workflows/python-tox-matrix-py3.yml@master
    with:
      fail-fast: false
  
