name: Push Test Build
on:
  push:
      branches:
        - '*'
        - '!main'

jobs:
  test-matrix:
    uses: softstream-link/workflows/.github/workflows/setuptools-pytest-matrix-py3.yml@v1
    with:
      fail-fast: false
    
  publish-test-pypi:
    needs: test-matrix
    uses: softstream-link/workflows/.github/workflows/setuptools-twine-pypi-publish.yml@v1
    with:
      environment: test
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }} # needs both environment and secrets to work https://github.com/actions/runner/issues/1490
    
  



  